### ISSUE TITLE
Camera takes input but doesn't work

### ISSUE THREAD

**Issue by castrojo** [ogra1/zoom-snap#1]
Hi ogra! Thanks for working on this: 

I've installed the snap from edge, `zoom-client (edge) 3.5.374815.0324` and connected the interfaces as mentioned in the instructions. Everything appears to be working except the camera. Zoom itself sees the camera device, and the light is glowing on it, it's just sending a black screen instead of my face. I don't see any output on the terminal when running it via `snap run zoom-client` or any obvious errors. 

![Screenshot from 2020-03-26 15-11-42](https://user-images.githubusercontent.com/1264109/77687013-30923880-6f74-11ea-84ff-5f1157c60822.png)

**Comment by ogra1** [comment]
this is exactly the reason why it is still in the edge channel, cameras work fine when they are builtin in laptops but not when connected via USB ... i'm poking around on that since a while

**Comment by castrojo** [comment]
If you need help testing or more data let me know!

**Comment by castrojo** [comment]
Revision 35 has fixed this for me on the 2 machines I was seeing this problem on! I owe you a beer!

**Comment by ogra1** [comment]
well, only semi-fixed ... it breaks on all nvidia systems now ... still needs a bit more work

**Comment by ogra1** [comment]
ok, nvidia half way fixed too ... closing
