### ISSUE TITLE
Error when launching zoom-client

### ISSUE THREAD

**Issue by danhper** [ogra1/zoom-snap#10]
Hi,
I get the following issue when running the `zoom-client` command.

```
/snap/zoom-client/64/bin/launcher.sh: 9: [: /var/lib/snapd/lib/gl/libnvidia-glcore.so: unexpected operator
```

I'm running this on ArchLinux and my `/var/lib/snapd/lib/gl/` directory is empty. I am using the nvidia drivers in X11.
Let me know if you need any other information.

Thanks.

**Comment by ogra1** [comment]
can you attach the logfile from:
```
~/snap/zoom-client/current/.zoom/logs/zoom-terminal.log
```

**Comment by ogra1** [comment]
this should be fixed in newer releases of the snap (it does not do any special-casing for nvidia anymore but relies fully on the snap system to set up graphics drivers now)
