### ISSUE TITLE
Sharing sound when sharing video is not working

### ISSUE THREAD

**Issue by cswertz** [ogra1/zoom-snap#104]
If a video is presented using "share screen" with "share sound" turned on, the sound is not transmitted. It is working with the zoom deb-package from the zoom homepage, so it might be a problem with the sound settings for the snap package.

**Comment by Fuseteam** [comment]
this is possibly a duplicate of #3

**Comment by cswertz** [comment]
Right - sorry, I read the issues but somehow overlooked that one. THX!
