### ISSUE TITLE
Latest snap version of the client does not launch on Ubuntu 20.04

### ISSUE THREAD

**Issue by daisukixci** [ogra1/zoom-snap#110]
Since yesterday my zoom client does not open on Ubuntu 20.04 and seems to fails with a segfault joined logs I found

```
❯ snap info zoom-client
name:      zoom-client
summary:   ZOOM Cloud Meetings
publisher: Oliver Grawert (ogra)
store-url: https://snapcraft.io/zoom-client
contact:   ogra@ubuntu.com?subject=zoom-client
license:   unset
description: |
  Video conferencing with real-time messaging and content sharing

  https://zoom.us/ provides simplified video conferencing, whiteboard sharing
  and messaging across any device. This is an unofficial re-pack of the debian
  package provided by zoom.us
commands:
  - zoom-client
snap-id:      76rrD7USwCJrZgepbRk7UdFEWON3tVKX
tracking:     latest/stable
refresh-date: today at 17:29 CEST
channels:
  latest/stable:    5.10.3.2778 2022-04-21 (175) 369MB
```
Log file
[zoom_stdout_stderr.log](https://github.com/ogra1/zoom-snap/files/8542342/zoom_stdout_stderr.log)

**Comment by jpseara** [comment]
Observing the same issue in Jammy.

@daisukixci can you kindly let me know how do you generate that output file so I can try to compare to see if I have the same issue?

**Comment by Fuseteam** [comment]
appearently it also doesn't open on 18.04, 
to make things worse zoom is mandating 5.10 so this is critical
the good news is that the deb version does work normally

**Comment by daisukixci** [comment]
Probably same issue as #112

**Comment by Fuseteam** [comment]
@jpseara yeah i've fallen back on the deb version for now, but it would nice to get this fixed. less technical people aren't able to use the browser version that easily, or update themselves really

**Comment by jpseara** [comment]
> @jpseara yeah i've fallen back on the deb version for now, but it would nice to get this fixed. less technical people aren't able to use the browser version that easily, or update themselves really

Agreed. Unfortunately this snap is maintained by a single person (which is doing a fantastic job by the way!) and not by Zoom themselves. Which means that there will always be some delays when getting new releases or fix ongoing problems.

**Comment by vasi** [comment]
Looks liike the Flatpak is having similar issues: https://github.com/flathub/us.zoom.Zoom/issues/315

**Comment by daisukixci** [comment]
> > @jpseara yeah i've fallen back on the deb version for now, but it would nice to get this fixed. less technical people aren't able to use the browser version that easily, or update themselves really
> 
> Agreed. Unfortunately this snap is maintained by a single person (which is doing a fantastic job by the way!) and not by Zoom themselves. Which means that there will always be some delays when getting new releases or fix ongoing problems.

No doubt about it, if I had been more familiar with snap (zoom is the first one I use), I could have known I could revert, and problem would have been fixed, but I purged :man_facepalming:

**Comment by Fuseteam** [comment]
> > @jpseara yeah i've fallen back on the deb version for now, but it would nice to get this fixed. less technical people aren't able to use the browser version that easily, or update themselves really
> 
> Agreed. Unfortunately this snap is maintained by a single person (which is doing a fantastic job by the way!) and not by Zoom themselves. Which means that there will always be some delays when getting new releases or fix ongoing problems.

don't worry, i know. just doing my part in confirming a critical bug ;)

**Comment by daisukixci** [comment]
I stop using the snap myself, but it seems it has been fixed, so i'm closing this one. Thanks a lot for your work.

**Comment by jrisi256** [comment]
Hi,

I tried downloading the snap version of Zoom on Ubuntu 22.04 using the latest=edge channel (because every other channel does not work. The application fails to even launch).

However, it fails to install with the following error:

`sudo snap install zoom-client --channel=latest/edge`

```
error: cannot perform the following tasks:
- Run configure hook of "zoom-client" snap if present (run hook "configure": /snap/zoom-client/201/usr/bin/fc-cache: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory)
```
Version of snap and ubuntu:

`snap --version`

```
snap    2.58.3
snapd   2.58.3
series  16
ubuntu  22.04
kernel  5.19.0-35-generic
```
If I can provide more information, let me know.

**Comment by fggec** [comment]
same here
`run hook "configure": /snap/zoom-client/201/usr/bin/fc-cache: error while loading shared libraries: libfontconfig.so.1: cannot open shared object file: No such file or directory`

**Comment by albertodiazdorado** [comment]
@daisukixci what do you use instead? I still cannot upgrade my zoom snap

**Comment by daisukixci** [comment]
I use the official Deb that we host in an internal mirror

**Comment by albertodiazdorado** [comment]
I was really hoping for a simpler solution, but I guess I will have to accept that there is not one :sweat_smile: 

Thanks!
