### ISSUE TITLE
Zoom lauch issue

### ISSUE THREAD

**Issue by siddheshsagar** [ogra1/zoom-snap#115]
Whenever i tried to launch zoom-client through teminal i get the message such as "Testing for explicit PulseAudio choice... 
...and PulseAudio has been explicitly chosen, so using it.". 
I have installed zoom from terminal using  **sudo snap install zoom-client**command and tried to launches through **zoom-client**.
but then get the message and zoom can't launches.
![zzzzz](https://user-images.githubusercontent.com/77565933/165983142-cfa8cbd7-e6e6-4ab9-9c96-ee204b19ad9f.png)

**Comment by Fuseteam** [comment]
um pretty sure this is related to #93

**Comment by Fuseteam** [comment]
oops wrong one meant #110

**Comment by siddheshsagar** [comment]
Refer #110
