### ISSUE TITLE
Client Freezes - i915

### ISSUE THREAD

**Issue by GaberSegs** [ogra1/zoom-snap#12]
Hello,

Using a laptop zoom client runs in some issues with freezing:

[Tue Apr 21 16:30:12 2020] i915 0000:00:02.0: GPU HANG: ecode 9:0:0x00000000, hang on rcs0
[Tue Apr 21 16:30:12 2020] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
[Tue Apr 21 16:30:20 2020] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
[Tue Apr 21 16:30:35 2020] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
[Tue Apr 21 16:30:43 2020] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
[Tue Apr 21 16:30:51 2020] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
[Tue Apr 21 16:30:59 2020] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0

Graphics:
Intel Corporation Device 3ea0 (rev 02), using i915 kernel drivers
Kernel:
5.3.0-46-generic
OS:
elementary OS 5.1.3 Hera - Tested also on Ubuntu, same issue.

**Comment by ogra1** [comment]
can you attach
```
~/snap/zoom-client/current/.zoom/logs/zoom-terminal.log
```

**Comment by GaberSegs** [comment]
**/home/gaber/snap/zoom-client/current/.zoom/logs/zoom-terminal.log**
ZoomLauncher started.
cmd line: 
CreateReportChannel bp_server_fd=4
$HOME = /home/gaber/snap/zoom-client/64 
export SSB_HOME=/home/gaber/snap/zoom-client/64/.zoom; export QSG_INFO=1; export LD_LIBRARY_PATH=/snap/zoom-client/64/zoom; export BREAKPAD_CLIENT_FD=3; /snap/zoom-client/64/zoom/zoom "" 
No PulseAudio daemon running, or not running as session daemon.
zoom started.
Gtk-Message: 15:37:12.817: Failed to load module "pantheon-filechooser-module"
Gtk-Message: 15:37:13.193: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:37:13.217: Failed to load module "canberra-gtk-module"
ZoomLauncher started.
cmd line: 
CreateReportChannel bp_server_fd=4
QApplication: invalid style override passed, ignoring it.
$HOME = /home/gaber/snap/zoom-client/64 
export SSB_HOME=/home/gaber/snap/zoom-client/64/.zoom; export QSG_INFO=1; export LD_LIBRARY_PATH=/snap/zoom-client/64/zoom; export BREAKPAD_CLIENT_FD=3; /snap/zoom-client/64/zoom/zoom "" 
Exit zoom as another zoom instance is running!
No PulseAudio daemon running, or not running as session daemon.
zoom started.
Gtk-Message: 15:37:14.259: Failed to load module "pantheon-filechooser-module"
Gtk-Message: 15:37:14.393: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:37:14.398: Failed to load module "canberra-gtk-module"
QApplication: invalid style override passed, ignoring it.
Exit zoom as another zoom instance is running!
No PulseAudio daemon running, or not running as session daemon.
No PulseAudio daemon running, or not running as session daemon.
Client: Breakpad is using Client-Server Mode! client fd = 3
Client: Breakpad is using Client-Server Mode! client fd = 3
success to create child process,status is 0.
zoom exited normally.
run zoom successfully,exit code is 0.
ZoomLauncher exit.
success to create child process,status is 0.
zoom exited normally.
run zoom successfully,exit code is 0.
ZoomLauncher exit.

**/home/gaber/snap/zoom-client/current/.zoom/logs/zoom-terminal.log.old**
ZoomLauncher started.
cmd line: 
CreateReportChannel bp_server_fd=4
$HOME = /home/gaber/snap/zoom-client/64 
export SSB_HOME=/home/gaber/snap/zoom-client/64/.zoom; export QSG_INFO=1; export LD_LIBRARY_PATH=/snap/zoom-client/64/zoom; export BREAKPAD_CLIENT_FD=3; /snap/zoom-client/64/zoom/zoom "" 
No PulseAudio daemon running, or not running as session daemon.
zoom started.
Gtk-Message: 16:25:14.984: Failed to load module "pantheon-filechooser-module"
Gtk-Message: 16:25:15.032: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:25:15.033: Failed to load module "canberra-gtk-module"
QApplication: invalid style override passed, ignoring it.
Exit zoom as another zoom instance is running!
No PulseAudio daemon running, or not running as session daemon.
Client: Breakpad is using Client-Server Mode! client fd = 3
success to create child process,status is 0.
zoom exited normally.
run zoom successfully,exit code is 0.
ZoomLauncher exit.
ZoomLauncher started.
cmd line: 
CreateReportChannel bp_server_fd=4
$HOME = /home/gaber/snap/zoom-client/64 
export SSB_HOME=/home/gaber/snap/zoom-client/64/.zoom; export QSG_INFO=1; export LD_LIBRARY_PATH=/snap/zoom-client/64/zoom; export BREAKPAD_CLIENT_FD=3; /snap/zoom-client/64/zoom/zoom "" 
No PulseAudio daemon running, or not running as session daemon.
zoom started.
Gtk-Message: 15:37:12.823: Failed to load module "pantheon-filechooser-module"
Gtk-Message: 15:37:13.193: Failed to load module "canberra-gtk-module"
Gtk-Message: 15:37:13.217: Failed to load module "canberra-gtk-module"
QApplication: invalid style override passed, ignoring it.
[CZPClientLogMgr::LogClientEnvironment] [MacAddr: 60:F2:62:BD:81:11][client: Linux][OS: Ubuntu Core 18][Hardware: CPU Core:4 Frenquency:1.6 G Memory size:7807MB CPU Brand:Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz GPU Brand:][Req ID: ]
Linux Client Version is 3.5.385850.0413
QSG_RENDER_LOOP is 
XDG_CURRENT_DESKTOP = Pantheon;   GDMSESSION = pantheon
Graphics Card Info:: 
Zoom package arch is 64bit, runing OS arch is x86_64
Client: Breakpad is using Client-Server Mode! client fd = 3
Error: Send error, 22 Invalid argument
Error: Send error, 22 Invalid argument
Error: Send error, 22 Invalid argument
qt.scenegraph.general: QSG: basic render loop
qt.scenegraph.general: Using sg animation driver
qt.svg: link image0 hasn't been detected!
qt.svg: :/images/wechat.svg:10:6: Could not resolve property: pattern0
qt.scenegraph.general: texture atlas dimensions: 1024x512
qt.scenegraph.general: R/G/B/A Buffers:    8 8 8 8
qt.scenegraph.general: Depth Buffer:       24
qt.scenegraph.general: Stencil Buffer:     8
qt.scenegraph.general: Samples:            -1
qt.scenegraph.general: GL_VENDOR:          Intel Open Source Technology Center
qt.scenegraph.general: GL_RENDERER:        Mesa DRI Intel(R) UHD Graphics (Whiskey Lake 3x8 GT2) 
qt.scenegraph.general: GL_VERSION:         3.0 Mesa 19.2.8
qt.scenegraph.general: GL_EXTENSIONS:      GL_KHR_blend_equation_advanced_coherent GL_EXT_multi_draw_arrays GL_EXT_texture_compression_s3tc GL_ARB_framebuffer_sRGB GL_EXT_bgra GL_NV_texgen_reflection GL_EXT_texture_object GL_ARB_texture_compression GL_ARB_program_interface_query GL_ARB_vertex_array_bgra GL_ARB_clip_control GL_EXT_stencil_wrap GL_MESA_window_pos GL_AMD_shader_stencil_export GL_ARB_texture_env_combine GL_EXT_texture_shadow_lod GL_EXT_texture_lod_bias GL_ARB_post_depth_coverage GL_EXT_framebuffer_sRGB GL_ARB_pipeline_statistics_query GL_EXT_shader_framebuffer_fetch GL_EXT_texture_compression_dxt1 GL_ARB_sampler_objects GL_NV_texture_barrier GL_ARB_texture_cube_map GL_EXT_texture_sRGB_R8 GL_EXT_copy_texture GL_ARB_multi_bind GL_NV_compute_shader_derivatives GL_ARB_shader_texture_lod GL_ARB_framebuffer_no_attachments GL_ARB_vertex_shader GL_EXT_pixel_buffer_object GL_ARB_shader_clock GL_ARB_fragment_shader GL_KHR_texture_compression_astc_sliced_3d GL_ARB_shader_image_size GL_INTEL_performance_query GL_ARB_shader_group_vote GL_ARB_provoking_vertex GL_ARB_derivative_control GL_ARB_ES2_compatibility GL_EXT_texture_filter_anisotropic GL_ARB_robust_buffer_access_behavior GL_KHR_parallel_shader_compile GL_EXT_stencil_two_side GL_EXT_vertex_array GL_ARB_robustness GL_NV_texture_rectangle GL_EXT_texture_integer GL_ARB_texture_border_clamp GL_ARB_texture_compression_bptc GL_3DFX_texture_compression_FXT1 GL_SUN_multi_draw_arrays GL_ARB_transform_feedback_instanced GL_ATI_texture_float GL_AMD_shader_trinary_minmax GL_EXT_texture GL_ARB_shader_storage_buffer_object GL_EXT_blend_minmax GL_ARB_compressed_texture_pixel_storage GL_EXT_texture_env_add GL_ARB_texture_query_lod GL_ARB_indirect_parameters GL_EXT_texture_compression_rgtc GL_ARB_sync GL_ARB_transform_feedback2 GL_EXT_point_parameters GL_ARB_shader_draw_parameters GL_EXT_shadow_funcs GL_INGR_blend_func_separate GL_EXT_vertex_array_bgra GL_EXT_shader_framebuffer_fetch_non_coherent GL_ARB_fragment_program_shadow GL_IBM_rasterpos_clip GL_ARB_shading_language_100 GL_ARB_fragment_program GL_ARB_shader_image_load_store GL_AMD_query_buffer_object GL_EXT_framebuffer_multisample GL_SGIS_generate_mipmap GL_ARB_blend_func_extended GL_ARB_half_float_pixel GL_EXT_subtexture GL_ARB_texture_env_add GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_blit GL_AMD_multi_draw_indirect GL_AMD_draw_buffers_blend GL_ATI_draw_buffers GL_EXT_shader_integer_mix GL_EXT_texture_sRGB GL_ARB_shader_atomic_counter_ops GL_ARB_shader_ballot GL_ARB_explicit_attrib_location GL_KHR_context_flush_control GL_ARB_texture_mirrored_repeat GL_ARB_get_program_binary GL_ARB_shader_precision GL_ARB_fragment_coord_conventions GL_ARB_internalformat_query GL_EXT_texture3D GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_timer_query GL_EXT_texture_env_combine GL_AMD_depth_clamp_separate GL_ARB_shading_language_420pack GL_EXT_shader_samples_identical GL_EXT_texture_edge_clamp GL_EXT_texture_rectangle GL_ARB_multi_draw_indirect GL_ARB_color_buffer_float GL_ARB_texture_multisample GL_EXT_texture_sRGB_decode GL_NV_fragment_shader_interlock GL_ARB_clear_buffer_object GL_EXT_texture_env_dot3 GL_EXT_polygon_offset_clamp GL_EXT_transform_feedback GL_ARB_invalidate_subdata GL_EXT_texture_shared_exponent GL_EXT_texture_cube_map GL_SGIS_texture_lod GL_EXT_separate_specular_color GL_EXT_draw_instanced GL_ARB_shader_objects GL_ARB_copy_buffer GL_ARB_fragment_layer_viewport GL_ARB_shader_atomic_counters GL_ARB_vertex_array_object GL_ARB_separate_shader_objects GL_ARB_multitexture GL_ARB_depth_buffer_float GL_KHR_robustness GL_EXT_packed_float GL_ARB_draw_buffers GL_MESA_texture_signed_rgba GL_NV_depth_clamp GL_ARB_depth_texture GL_S3_s3tc GL_ARB_texture_env_crossbar GL_ARB_texture_rg GL_ARB_texture_view GL_EXT_timer_query GL_IBM_texture_mirrored_repeat GL_ARB_point_parameters GL_ARB_texture_storage GL_SGIS_texture_border_clamp GL_ARB_texture_rgb10_a2ui GL_EXT_blend_func_separate GL_ARB_texture_env_dot3 GL_APPLE_object_purgeable GL_ARB_conditional_render_inverted GL_EXT_fog_coord GL_ARB_depth_clamp GL_ARB_shadow GL_ARB_query_buffer_object GL_KHR_texture_compression_astc_ldr GL_ARB_texture_compression_rgtc GL_KHR_blend_equation_advanced GL_ARB_framebuffer_object GL_ARB_instanced_arrays GL_ARB_arrays_of_arrays GL_ARB_vertex_attrib_binding GL_ARB_map_buffer_alignment GL_ARB_ES3_compatibility GL_ARB_shader_bit_encoding GL_IBM_multimode_draw_arrays GL_ARB_transform_feedback3 GL_EXT_blend_equation_separate GL_ARB_point_sprite GL_NV_packed_depth_stencil GL_ARB_internalformat_query2 GL_ARB_shader_texture_image_samples GL_ARB_texture_filter_anisotropic GL_NV_light_max_exponent GL_ARB_texture_query_levels GL_EXT_compiled_vertex_array GL_EXT_gpu_program_parameters GL_EXT_framebuffer_object GL_ARB_texture_barrier GL_ARB_texture_storage_multisample GL_ARB_ES3_1_compatibility GL_SGIS_texture_edge_clamp GL_ARB_polygon_offset_clamp GL_EXT_secondary_color GL_AMD_seamless_cubemap_per_texture GL_EXT_draw_range_elements GL_ARB_texture_stencil8 GL_EXT_rescale_normal GL_EXT_packed_pixels GL_ARB_seamless_cube_map GL_ARB_occlusion_query GL_ARB_texture_gather GL_EXT_blend_color GL_ARB_map_buffer_range GL_ARB_compute_shader GL_APPLE_packed_pixels GL_NV_texture_env_combine4 GL_EXT_texture_snorm GL_ANGLE_texture_compression_dxt3 GL_NV_primitive_restart GL_NV_blend_square GL_ARB_shading_language_packing GL_ARB_buffer_storage GL_ANGLE_texture_compression_dxt5 GL_ARB_draw_elements_base_vertex GL_ARB_fragment_shader_interlock GL_OES_EGL_image GL_MESA_shader_integer_functions GL_ARB_occlusion_query2 GL_ARB_texture_cube_map_array GL_ARB_texture_rectangle GL_MESA_pack_invert GL_EXT_texture_swizzle GL_NV_fog_distance GL_ATI_separate_stencil GL_ARB_transpose_matrix GL_EXT_blend_subtract GL_ARB_copy_image GL_KHR_debug GL_ARB_parallel_shader_compile GL_ATI_texture_env_combine3 GL_EXT_texture_array GL_AMD_texture_texture4 GL_INTEL_shader_atomic_float_minmax GL_ARB_window_pos GL_NV_conditional_render GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_non_power_of_two GL_ARB_half_float_vertex GL_OES_read_format GL_EXT_packed_depth_stencil GL_ARB_draw_instanced GL_ARB_shader_stencil_export GL_ARB_cull_distance GL_ARB_draw_indirect GL_ARB_transform_feedback_overflow_query GL_ATI_blend_equation_separate GL_EXT_provoking_vertex GL_ARB_texture_swizzle GL_ARB_draw_buffers_blend GL_AMD_conservative_depth GL_EXT_abgr GL_ARB_debug_output GL_EXT_draw_buffers2 GL_ARB_seamless_cubemap_per_texture GL_ARB_explicit_uniform_location GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_sample_shading GL_ARB_pixel_buffer_object GL_ARB_uniform_buffer_object GL_ARB_get_texture_sub_image GL_ARB_conservative_depth GL_ARB_stencil_texturing GL_ARB_clear_texture GL_KHR_no_error GL_ARB_texture_float GL_KHR_robust_buffer_access_behavior GL_ARB_multisample GL_ARB_vertex_program GL_ARB_vertex_buffer_object
qt.scenegraph.general: Max Texture Size:  16384
qt.scenegraph.general: Debug context:     false
CSBConfUI::OnConfStatusChanged  UI_CMD_SHARE_READYQCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
WorkerBase::loop() normal exit, fds[0].revents & POLLIN = trueWorkerBase::loop() normal exit, fds[0].revents & POLLIN = trueWorkerBase::loop() normal exit, fds[0].revents & POLLIN = trueWorkerBase::loop() normal exit, fds[0].revents & POLLIN = true

**Comment by ogra1** [comment]
thank you ! 

there seems to be an issue with i915 and the kernel:
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1872001

can you try going back to the former kernel version and see if that fixes it for you ?

**Comment by GaberSegs** [comment]
Hello, changing the kernel helps, solves the issue. thank you!!

**Comment by ogra1** [comment]
awesome
