### ISSUE TITLE
Zoom crashes on startup after upgrade to 5.15.11.7239

### ISSUE THREAD

**Issue by hvbakel** [ogra1/zoom-snap#129]
Version 5.15.11.7239 was just pushed to the stable channel. Unfortunately this version crashes immediately during startup on an up to date ubuntu 22.04 system.

**Comment by mojibake-umd** [comment]
Ditto. Upgraded to 5.15.5.5603 but I had to revert back to  5.15.2.4260. Also Ubuntu 22.04 (being a snap most OS would be Ubuntu of some sort)

**Comment by hvbakel** [comment]
Appears fixed as of version 5.16.5.303.
