### ISSUE TITLE
“realpath: '': No such file or directory” errors when trying to start zoom-client

### ISSUE THREAD

**Issue by pachulo** [ogra1/zoom-snap#20]
Since today, I'm seeing this when trying to start zoom-client:
```
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
```
And the Zoom window disappears. It was working fine last week. I'm on Ubuntu 18.04

**Comment by pachulo** [comment]
OK, ignore this. This was due to an updated nvidia driver and me not rebooting; sorry for the noise!

**Comment by ogra1** [comment]
yeah, the realpath messages, while annoying, come from the snapcraft desktop launchers and are harmless ...
