### ISSUE TITLE
Screen/Whiteboard annotation issues

### ISSUE THREAD

**Issue by lilzy218** [ogra1/zoom-snap#27]
#Hi,

After installing the latest update from May 13 for Linux Mint ( update number 5.0.403652.0509), I am no longer able to annotate the screen in whiteboard or share screen mode. Either the text disappears completely, or random letters/symbols are displayed. 
This facility is essential to me as a teacher who has been forced to work online in the current climate. I downloaded the previous version and there were no longer problems. Just wanted to report this problem in case anyone else has experienced the same. I've attached a screen shot to show what I mean.

Thanks!

![zoom issue](https://user-images.githubusercontent.com/65393680/82031302-93a96d00-9691-11ea-85e7-1c717f4d94c7.png)

**Comment by ogra1** [comment]
can you tell me which the exact revisions were that you used (which worked and which failed) so i can compare them ?

**Comment by lilzy218** [comment]
Hi,
I updated with the 'latest/stable 5.0.403652.0509, then reverted back to 'latest/candidate 5.0.399860.0429' and it seems to be working fine so far. Does that help at all? Apologies, I'm not too knowledgeable about technology...
Many thanks!

**Comment by ogra1** [comment]
this helps a lot, thanks i'll research what changed ...

**Comment by ogra1** [comment]
there is a new build in the edge channel that should work fine with text annotations ...

**Comment by lilzy218** [comment]
Sorry, what/where is the edge channel?

**Comment by ogra1** [comment]
well, let me just release it ... i haven't found any regressions in testing here ... the latest version in stable is now at revision 81 so just try with the latest ...

**Comment by ogra1** [comment]
i believe that revision 87 (5.0.418682.0603 now in the stable channel) fully solves this issue
