### ISSUE TITLE
zoom-client can not be opened after update via snapd (openSUSE Leap 15.1)

### ISSUE THREAD

**Issue by skriesch** [ogra1/zoom-snap#29]
2 days ago I have received an update for zoom-client via snapd. I was not able to use the zoom client for a conference today. The app has been closed directly on **openSUSE Leap 15.1**.

Time of the changes:
> ~> sudo snap changes
> ID   Status  Spawn                      Ready                      Summary
> 81   Done    2 days ago, at 16:45 CEST  2 days ago, at 16:45 CEST  Auto-refresh snaps "zoom-client", "dotnet-sdk"

Output of the try to update manually:

> ~> sudo snap refresh zoom-client
> error: cannot perform the following tasks:
> - Run post-refresh hook of "zoom-client" snap if present (run hook "post-refresh": 
> -----
> realpath: '': No such file or directory
> realpath: '': No such file or directory
> realpath: '': No such file or directory
> realpath: '': No such file or directory
> realpath: '': No such file or directory
> realpath: '': No such file or directory
> realpath: '': No such file or directory
> realpath: '': No such file or directory
> /snap/zoom-client/81/bin/desktop-launch: line 345: cannot create temp file for here-document: No such file or directory
> g_module_open() failed for /snap/zoom-client/81/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-ani.so: libgdk_pixbuf-2.0.so.0: cannot open shared object file: No such file or directory
> g_module_open() failed for /snap/zoom-client/81/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-bmp.so: libgdk_pixbuf-2.0.so.0: cannot open shared object file: No such file or directory
> g_module_open() failed for /snap/zoom-client/81/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-gif.so: libgdk_pixbuf-2.0.so.0: cannot open shared object file: No such file or directory
> g_module_open() failed for /snap/zoom-client/81/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-icns.so: libgdk_pixbuf-2.0.so.0: cannot open shared object file: No such file or directory
> g_module_open() failed for /snap/zoom-client/81/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-ico.so: libgdk_pixbuf-2.0.so.0: cannot open shared object file: No such file or directory
> g_module_open() failed for /snap/zoom-client/81/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-jpeg.so: libjpeg.so.8: cannot open shared object file: No such file or directory
> g_module_open() failed for /snap/zoom-client/81/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so: libgdk_pixbuf-2.0.so.0: cannot open shared object file: No such file or directory
> g_module_open() failed for /snap/zoom-client/81/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-pnm.so: libgdk_pixbuf-2.0.so.0: cannot open shared object file: No such file or directory
> g_module_open() failed for /snap/zoom-client/81/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-qtif.so: libgdk_pixbuf-2.0.so.0: cannot open shared object file: No such file or directory
> g_module_open() failed for /snap/zoom-client/81/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so: librsvg-2.so.2: cannot open shared object file: No such file or directory
> g_module_open() failed for /snap/zoom-client/81/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-tga.so: libgdk_pixbuf-2.0.so.0: cannot open shared object file: No such file or directory
> g_module_open() failed for /snap/zoom-client/81/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-tiff.so: libtiff.so.5: cannot open shared object file: No such file or directory
> g_module_open() failed for /snap/zoom-client/81/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-xbm.so: libgdk_pixbuf-2.0.so.0: cannot open shared object file: No such file or directory
> g_module_open() failed for /snap/zoom-client/81/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-xpm.so: libgdk_pixbuf-2.0.so.0: cannot open shared object file: No such file or directory
> /snap/zoom-client/81/bin/build-ld-cache: line 14: cannot create temp file for here-document: No such file or directory

The zoom-client should work on all Linux distributions via snapd.

**Comment by ogra1** [comment]
oh, wow, that's gross, i'm really sorry that you hit this ... 
you can immediately roll back to the last version on disk with:

    sudo snap revert zoom-client

i'll take care to roll back the stable channel to the former version

**Comment by ogra1** [comment]
stable and edge are now both rolled back to revision 80, please check if this works for you... a simple

    snap refresh zoom-client 

should get you back on what the store provides

**Comment by skriesch** [comment]
I had to restart the system and all is working now again.
Thank you! :)
