### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by kz6fittycent** [ogra1/zoom-snap#3]
```
snap-id:      76rrD7USwCJrZgepbRk7UdFEWON3tVKX
tracking:     stable
refresh-date: today at 21:18 CDT
channels:
stable:    3.5.374815.0324 2020-03-29 (41) 193MB -
```

OS and Snap info:

```
snap --version
snap    2.39.3
snapd   2.39.3
series  16
solus   4.1
kernel  5.5.11-151.current
```

Getting the following error when attempting to connect `audio-record`

```
sudo snap connect zoom-client:audio-record
error: snap "zoom-client" has no plug named "audio-record"
```

**Comment by ogra1** [comment]
thanks for reporting the bug !
2.39 is pretty old (current is 2.43), the solus package should really get updated ...
i'll add the pulseaudio plug to the package with the next build in the edge channel, that should allow you to use audio recording on such an old snapd version as well ...

**Comment by ogra1** [comment]
please try with:
```
sudo snap refresh --edge zoom-client
```
(you want revision 48) ... and then:
```
sudo snap connect zoom-client:pulseaudio
```
... that should make audio recording work fine

**Comment by kz6fittycent** [comment]
NAILED IT!

Thanks for the fast response. You're right, Solus REALLY has to update the snap version to the latest. It's causing all kinds of issues with newer snaps being released.
