### ISSUE TITLE
After refreshing to revision 83, snap doesn't start any longer

### ISSUE THREAD

**Issue by oSoMoN** [ogra1/zoom-snap#30]
On Ubuntu 18.04.4, default GNOME desktop in an X11 session. The zoom snap was refreshed from revision 80 to revision 83, and just after the refresh I verified that it still launched. However after rebooting the machine, it didn't launch any more. Reverting to revision 80 makes it launch again.

Here are the contents of `~/snap/zoom-client/current/.zoom/logs/zoom-terminal.log`:

    Cursor: DMZ-White
    ZoomLauncher started.
    cmd line: 
    CreateReportChannel bp_server_fd=4
    $HOME = /home/foobar/snap/zoom-client/83 
    export SSB_HOME=/home/foobar/snap/zoom-client/83/.zoom; export QSG_INFO=1; export LXXXXXXXXY_PATH=/snap/zoom-client/83/zoom; export BREAKPAD_CLIENT_FD=3; /snap/zoom-client/83/zoom/zoom "" 
    No PulseAudio daemon running, or not running as session daemon.
    zoom started.
    [CZPClientLogMgr::LogClientEnvironment] [MacAddr: AA:BB:CC:DD:EE:FF][client: Linux][OS: Ubuntu Core 18][Hardware: CPU Core:4 Frenquency:1 G Memory size:7828MB CPU Brand:Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz GPU Brand:][Req ID: ]
    Linux Client Version is 5.0.413237.0524
    QSG_RENDER_LOOP is 
    XDG_CURRENT_DESKTOP = ubuntu:GNOME;   GDMSESSION = ubuntu
    Graphics Card Info:: 
    Zoom package arch is 64bit, runing OS arch is x86_64
    Client: Breakpad is using Client-Server Mode! client fd = 3
    Error: Send error, 101 Network is unreachable
    Error: Send error, 101 Network is unreachable
    Error: Send error, 101 Network is unreachable
    Could not initialize GLX
    Aborted
    success to create child process,status is 34304.
    zoom exited normally.
    Something went wrong while running zoom,exit code is 134.
    ZoomLauncher exit.

**Comment by oSoMoN** [comment]
Could it be that https://github.com/ogra1/zoom-snap/commit/ae5bbbff711944be22e1fd4515288d6e31698af4 fixes this?

**Comment by ogra1** [comment]
that was the plan ... it is revision 84

**Comment by oSoMoN** [comment]
I confirm that revision 84 launches again. Thanks!

**Comment by PranavBhattarai** [comment]
Bruh, help me. I am using Ubuntu 20.04.1 with GNOME 3.36.3 with Wayland but still, I am getting this warning message:
![Screenshot from 2020-08-30 09-58-17](https://user-images.githubusercontent.com/32763112/91651154-d4928980-eaa8-11ea-98e9-582a7b52c9c9.png)


What to do?

@oSoMoN @ogra1
