### ISSUE TITLE
There is no way to quit Zoom

### ISSUE THREAD

**Issue by stuartlangridge** [ogra1/zoom-snap#32]
As far as I can tell, Zoom cannot be quit once started.

It puts an icon in the notification area, but that icon has no menu attached to it. Closing the Zoom window does not remove the notification area icon, and does not quit the process. The Zoom window has a "menu" in the top panel with "New" and "Quit" options and that's it, and the "Quit" option doesn't do anything.

In Zoom settings there is the option to disable "when closed, minimize window to the notification area instead of the task bar". Disabling this option stops the notification area icon from appearing, but closing the Zoom window still doesn't quit the process, and there seems to be no way to get the Zoom window back again.

**Comment by ogra1** [comment]
There is an "Exit" option in the trayicon menu ... i cant really fix zoom bugs though, i just re-pack their binary ...

![Bildschirmfoto von 2020-06-02 20-19-40](https://user-images.githubusercontent.com/15386365/83555469-9f5cb680-a50e-11ea-9247-3700d0235ddf.png)

**Comment by stuartlangridge** [comment]
Apologies. _Signal_ doesn't have an exit menu item. Zoom does. So I am now embarrassed and will close this :-)
