### ISSUE TITLE
5.1.412382.0614 starts with huge ratio on hi-DPI monitor

### ISSUE THREAD

**Issue by brisssou** [ogra1/zoom-snap#36]
Hello,

Latest version is starting huge on the screen.

Command used to start it is (from `ps`):
`sh -c export SSB_HOME=/home/blaurencin/snap/zoom-client/88/.zoom; export QSG_INFO=1; export QT_AUTO_SCREEN_SCALE_FACTOR=1; export LXXXXXXXXY_PATH=/snap/zoom-client/88/zoom; export BREAKPAD_CLIENT_FD=3; /snap/zoom-client/88/zoom/zoom ""`
with previous version it was 
`sh -c export SSB_HOME=/home/blaurencin/snap/zoom-client/87/.zoom; export QSG_INFO=1; export LXXXXXXXXY_PATH=/snap/zoom-client/87/zoom; export BREAKPAD_CLIENT_FD=3; /snap/zoom-client/87/zoom/zoom ""`

I don't know if this is something that can be fixed in the snap… I did not find the `QT_AUTO_SCREEN_SCALE_FACTOR` string the snap folder using `grep -r` and launching the snap with the command above fails with libraries missing (I don't know jack about snap, sorry…)

Thanks for your help!

edit: well, it's pretty the return of #5

**Comment by ogra1** [comment]
hmm, this is weird, i definitely did not change the launcher (which exports his var) ... can you attach your zoom log from:

    ~/snap/zoom-client/current/.zoom/logs/zoom-terminal.log

**Comment by ogra1** [comment]
oh, i actually see what the error is ... zoom sets QT_AUTO_SCREEN_SCALE_FACTOR=1 (note the AUTO) ... this has never worked right ... what the launcher does is to compute the actual correct QT_SCALE_FACTOR= according to the dpi ... so with them forcing auto scaling the UI now gets scaled twice ... turning off the launcher still gets me a login screen that's nearly full-screen on a 4k display, i'll try to work around their enforcement to get the former behaviour back.

**Comment by ogra1** [comment]
revision 89 in the edge channel should now have the fix ... please test if this solves it for you:

    sudo snap refresh --edge zoom-client

once this got released to sthe stable channel you can switch back to stable with:

    sudo snap refresh --stable zoom-client

**Comment by brisssou** [comment]
This is great success!
It works fine for me on Ubuntu20.04

thanks a lot, that was fast :+1:
