### ISSUE TITLE
Social logins not working

### ISSUE THREAD

**Issue by Fuseteam** [ogra1/zoom-snap#39]
I am unable to login via social logins
It appears to properly spawn a browser window but the snap does not respond after logging in via the browser
I do have both the deb and snap version installed

**Comment by mojibake-umd** [comment]
Please see https://github.com/ogra1/zoom-snap/issues/14
Doing SSO login for work, I copy the "Launch Zoom" url link and run it on cli with xdg-open <link>.

**Comment by Fuseteam** [comment]
ohw that an interesting approach. in my case xdg-open will open the deb version for me

**Comment by Fuseteam** [comment]
social login seems to work now
