### ISSUE TITLE
client won't launch - old version

### ISSUE THREAD

**Issue by arkmundi** [ogra1/zoom-snap#40]
![ZoomClient](https://user-images.githubusercontent.com/7421910/87232987-59a6cf80-c391-11ea-8b13-0e68105b347c.png)
Shows client version:  5.1.422789.0705
![ZoomClient2](https://user-images.githubusercontent.com/7421910/87233047-e487ca00-c391-11ea-9b7d-07badbd5ffae.png)
When trying to join meetup, says:  Version: 3.5.374815.0324 and need at least 5.0
What give?

**Comment by ogra1** [comment]
if you open the tray icon from the top panel and pick the "about" item there, what version is shown there ?

**Comment by arkmundi** [comment]
The 3.5 version

**Comment by ogra1** [comment]
well, then you are not running the snap ... try using a terminal and do

    snap info zoom-client

also, try running ir as:

    snap run zoom-client 

and check the version again

**Comment by arkmundi** [comment]
$ snap info zoom-client
name:      zoom-client
summary:   ZOOM Cloud Meetings
publisher: Oliver Grawert (ogra)
store-url: https://snapcraft.io/zoom-client
contact:   ogra@ubuntu.com?subject=zoom-client
license:   Proprietary
description: |
  Video conferencing with real-time messaging and content sharing

  https://zoom.us provides simplified video conferencing, whiteboard sharing
  and messaging across any device. This is an unofficial re-pack of the
debian
  package provided by zoom.us

  The source code for the snap package can be found at
https://github.com/ogra1/zoom-snap

  Please file issues under https://github.com/ogra1/zoom-snap/issues
snap-id: 76rrD7USwCJrZgepbRk7UdFEWON3tVKX
channels:
  latest/stable:    5.1.422789.0705 2020-07-11 (92) 151MB -
  latest/candidate: 5.0.399860.0429 2020-05-12 (75) 148MB -
  latest/beta:      5.0.399860.0429 2020-05-12 (75) 148MB -
  latest/edge:      5.1.422789.0705 2020-07-07 (92) 151MB -

**Comment by ogra1** [comment]
well, either you omitted the last line when pasting or you do not have the snap installed at all, the last block of output should show which version you have installed, here is what i get at the end:
```
  The source code for the snap package can be found at https://github.com/ogra1/zoom-snap
  
  Please file issues under https://github.com/ogra1/zoom-snap/issues
commands:
  - zoom-client
snap-id:      76rrD7USwCJrZgepbRk7UdFEWON3tVKX
tracking:     latest/edge
refresh-date: 4 days ago, at 23:47 CEST
channels:
  latest/stable:    5.1.422789.0705 2020-07-11 (92) 151MB -
  latest/candidate: 5.0.399860.0429 2020-05-12 (75) 148MB -
  latest/beta:      5.0.399860.0429 2020-05-12 (75) 148MB -
  latest/edge:      5.1.422789.0705 2020-07-07 (92) 151MB -
installed:          5.1.422789.0705            (92) 151MB -
```

**Comment by arkmundi** [comment]
I'm good.  What I needed to do:
1> Synaptic Package Manger:  completely remove Zoom Client
2> Ubuntu Software (SNAP):  Remove (again, since it showed as installed)
3> Ubuntu Software (SNAP):  Install

So:  installed:          5.1.422789.0705            (92) 151MB -
... and apparently working.
