### ISSUE TITLE
Zoom doesn't stay logged in after exit

### ISSUE THREAD

**Issue by YamiYukiSenpai** [ogra1/zoom-snap#41]
Every time I force close Zoom, or restart my PC, the app doesn't log me back in automatically.

**Comment by ogra1** [comment]
Do you have the "Keep me signed in" checkbox set ? It definitely works for me ...

<img src="https://user-images.githubusercontent.com/15386365/87849677-9b33ff00-c8ea-11ea-8501-2dfa28b44947.png" height="50%" width="50%">

**Comment by YamiYukiSenpai** [comment]
Just checked, and it works. Thought I marked that.
Sorry about that. XD

**Comment by Fuseteam** [comment]
in the few cases social log in does work, it has a similar issue fwiw
