### ISSUE TITLE
the versions in the channel list look out of order

### ISSUE THREAD

**Issue by Fuseteam** [ogra1/zoom-snap#44]
i was looking at snap info zoom-client as the beta and candidate channels seems to have older versions then the stable channel
here's the output i see
```
 latest/stable:    5.2.446620.0816 2020-08-18 (94) 153MB -
  latest/candidate: 5.0.399860.0429 2020-05-12 (75) 148MB -
  latest/beta:      5.0.399860.0429 2020-05-12 (75) 148MB -
  latest/edge:      5.2.454870.0831 2020-09-02 (96) 150MB -
installed:          5.2.446620.0816            (94) 153MB -
```

**Comment by ogra1** [comment]
yes, this was on purpose ...
i typically do not use beta or candidate at all, if a new release comes out i test the edge version, if it passes all tests i do (i have a little checklist from former issues) i typically release to stable ...

now, if i make bigger packaging changes that might break in some corner cases or only on specific distros, i do keep the former working version in beta/candidate so i can point people to that to still keep a running install.

i should probably update them to match stable while i dont do such changes (i.e. the font handling fixes were such changes)

**Comment by Fuseteam** [comment]
ah interesting, that's an interesting way of using the channels

**Comment by Fuseteam** [comment]
as this is on purpose it's not really an issue, as such i'll just close this issue
