### ISSUE TITLE
Zoom cannot detect Virtual Camera

### ISSUE THREAD

**Issue by nonoymarte** [ogra1/zoom-snap#49]
Virtual camera not included in the video options in zoom.

Trying these on Ubuntu 20.04.
My virtual camera is visible and working in Google meet.

**Comment by ogra1** [comment]
zoom uses v4l to talk to the cameras, does your virtual camera expose a /dev/video* device ?

**Comment by nonoymarte** [comment]
Yes, i use v4l2 using the ff command:
sudo modprobe v4l2loopback devices=1 video_nr=99 card_label=VirtualCam exclusive_caps=1
on ls /dev/video*
i get /dev/video0  /dev/video1  /dev/video2  /dev/video3  /dev/video99

snap version output
snap    2.46.1+20.04
snapd   2.46.1+20.04
series  16
ubuntu  20.04
kernel  5.4.0-48-generic

**Comment by ogra1** [comment]
have you tried dropping exclusive_caps=1 from that line ? 

i know for sure that zoom can handle v4l2loopback devices normally, so it should work:

https://ograblog.wordpress.com/2020/05/06/using-the-new-12mp-pi-cam-for-video-conferencing-on-your-desktop/

**Comment by nonoymarte** [comment]
Hi @ogra1,

Zoom can now detect Virtual Camera after removing exclusive_caps=1.
Looks like I will have different configurations for v4l2loopback since having exclusive_caps=1 works with zoom but when removed disables detection in Google Meet.

Thanks

**Comment by nonoymarte** [comment]
If you have a better workaround or handling, i would appreciate it as i work with both Google Meet and Zoom...

In the meantime, closing this ticket now.
Thanks
