### ISSUE TITLE
Large ui on non hidpi display

### ISSUE THREAD

**Issue by LyzardKing** [ogra1/zoom-snap#5]
Hi!
I tried the snap, but on my 1080p 14" screen the ui is double what it's supposed to be.
If I rebuild the snap with the env variable `QT_AUTO_SCREEN_SCALE_FACTOR: 1` removed it works as intended.

**Comment by ogra1** [comment]
well, on a 4k 14" laptop it has the size of a postal stamp and is unreadable small if the audo-scaling is not used, while on a desktop with 22" screen at 1080p it seems normal when it *is* used, the slightly too big UI for some people seemed more acceptable to me than having it at a size where it is compltely unusable for a portion of users. 

I'll check if there is some some other way to do the scaling in a better manner. If that doesnt work out, I can try add some option ... ```snap set zoom-client hidpi-scaling=..." so it can be turned on/off.

**Comment by LyzardKing** [comment]
but it's not slightly too big.. it's not really usable, and the appindicator is doubled in size as well (in ubuntu mate 20.04)
I'll try and see if there's a better way to scale depending on display

**Comment by FMuro** [comment]
I experience the same issue. There's no way to see the bottom part of the UI, just in overview mode, where you can't interact with it.

![Screenshot from 2020-04-05 00-26-07](https://user-images.githubusercontent.com/17141976/78462611-1a9f1900-76d4-11ea-8ea6-6eca7d695c13.png)
![Screenshot from 2020-04-05 00-26-09](https://user-images.githubusercontent.com/17141976/78462612-1b37af80-76d4-11ea-9955-3b9a30b426d5.png)

**Comment by ogra1** [comment]
there is a new build in the edge channel that tries to be a bit cleverer WRT scaling and scales based on the current DPI ... please remove your local variable overrides and test the snap from edge (revision 52):
```
sudo snap refresh --edge zoom-client
```
please see if that scales it more appropriately ...

**Comment by LyzardKing** [comment]
@ogra1 It works as intended on my non hi-dpi display!
Thanks for looking into it!

**Comment by ogra1** [comment]
\o/

**Comment by FMuro** [comment]
I also confirm it.

**Comment by ogra1** [comment]
i released revision 52 to stable, you can switch your local installs back to the stable channel with:
```
sudo snap refresh --stable zoom-client
```
