### ISSUE TITLE
Cannot open meeting links

### ISSUE THREAD

**Issue by glebbelov** [ogra1/zoom-snap#50]
With the DEB package, when clicking a meeting link in the browser, it would open Zoom automatically and start the meeting. With the snap package it happens only sometimes. I have Kubuntu 20.04.

**Comment by ogra1** [comment]
this is a snapd shortcoming (not allowing a snap to register mime types) and handled in 

https://github.com/ogra1/zoom-snap/issues/14#issuecomment-618250812
