### ISSUE TITLE
Zoom client does not load in Ubuntu 20.10 beta (Groovy Gorilla) under Wayland

### ISSUE THREAD

**Issue by thedefectiveram** [ogra1/zoom-snap#51]
Switched to Wayland on my newly (minimally) installed system (as of yesterday). Installed zoom client (snap version) run fine under X but not under Wayland. I have attached the logs.
[zoom_stdout_stderr.log](https://github.com/ogra1/zoom-snap/files/5328580/zoom_stdout_stderr.log)
[zoom-terminal.log](https://github.com/ogra1/zoom-snap/files/5328581/zoom-terminal.log)

**Comment by ogra1** [comment]
this is the issue ... 
```
Fontconfig warning: "/etc/fonts/fonts.conf", line 5: unknown element "its:rules"
Fontconfig warning: "/etc/fonts/fonts.conf", line 6: unknown element "its:translateRule"
Fontconfig error: "/etc/fonts/fonts.conf", line 6: invalid attribute 'translate'
Fontconfig error: "/etc/fonts/fonts.conf", line 6: invalid attribute 'selector'
Fontconfig error: "/etc/fonts/fonts.conf", line 7: invalid attribute 'xmlns:its'
Fontconfig error: "/etc/fonts/fonts.conf", line 7: invalid attribute 'version'
Fontconfig warning: "/etc/fonts/fonts.conf", line 9: unknown element "description"
```
you might be able to work around it by re-generating the font cache like:

```
sudo rm /var/cache/fontconfig/*
rm ~/.cache/fontconfig/*
fc-cache -r
```

**Comment by thedefectiveram** [comment]
Did that ran ran Zoom and and no go. Tried launching it in the terminal and got this error
mram@Inspiron-3451:~/snap/zoom-client/current/.zoom/logs$ zoom-client
xrdb: Connection refused
xrdb: Can't open display ':0'
mram@Inspiron-3451:~/snap/zoom-client/current/.zoom/logs$

**Comment by ogra1** [comment]
yeah, i'm pretty sure wayland denies running X11 apps from the terminal

**Comment by ogra1** [comment]
looks like 

https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1897224

is related ... quoting from there:

```
On groovy Xwayland has parameters "-extension SECURITY", while focal does not.
```

so this needs to be fixed in snapd, not much the zoom snap can do about

**Comment by thedefectiveram** [comment]
Thanks marked a effecting me.

**Comment by abitrolly** [comment]
Doesn't work on Fedora 33 too.
```
➜  ~ zoom-client          
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
xrdb: Connection refused
xrdb: Can't open display ':2'
```

**Comment by ogra1** [comment]
well, https://github.com/snapcore/snapd/pull/9530 got merged 3 days ago, the fix should be in the edge channel of snapd already for people using the snapd snap, i guess the next fedora rpm build of snapd will have it too.

**Comment by ogra1** [comment]
i believe this has long been fixed via the above snapd commit ... please re-open in case it unexpectedly still occurs
