### ISSUE TITLE
Current the zoom client on ubuntu 20.04 just can not be lanuched

### ISSUE THREAD

**Issue by SiZhan9** [ogra1/zoom-snap#54]
Please fix it, the zoom client works fine last week, but today, it can not open anyway, The only change I made is to update me ryzen gpu driver, if I open the zoom from the terminal, the response is that" Trying to use PulseAudio instead of ALSA..." and a window just pop up but then disappear, NO idea why this happens, please help! In the zoom is not even show up in the process I observe in the system monitor

**Comment by ogra1** [comment]
can you please attach the full output of:
```snap version```

as well as the files:
```~/snap/zoom-client/current/.zoom/logs/zoom-terminal.log```
and
```~/snap/zoom-client/current/.zoom/logs/zoom_stdout_stderr.log```

**Comment by SiZhan9** [comment]
snap version
snap    2.47.1+20.04
snapd   2.47.1+20.04
series  16
ubuntu  20.04
kernel  5.4.0-52-generic

Log files are attached:
[zoom_stdout_stderr.log](https://github.com/ogra1/zoom-snap/files/5488469/zoom_stdout_stderr.log)
[zoom-terminal.log](https://github.com/ogra1/zoom-snap/files/5488470/zoom-terminal.log)

**Comment by ogra1** [comment]
hmm, this is an issue with your graphics driver:
```
/usr/share/libdrm/amdgpu.ids: No such file or directory
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: radeonsi
```

are you using the default driver shipped with the distro ? 
also, are you running Xorg or the wayland session ?

**Comment by SiZhan9** [comment]
Thanks for pointing it out, I am not famiiar with the sesssion, but as you pointed out, I uninstailled the gpu driver, then zoom works, thanks!

**Comment by ogra1** [comment]
thanks for the feedback
