### ISSUE TITLE
Versions Don't Match: Zoom Client & Snap Store

### ISSUE THREAD

**Issue by personalizedrefrigerator** [ogra1/zoom-snap#59]
## Description
The version `zoom-client` lists in its about page and the version displayed in the snap store don't match -- `zoom-client` reports that it is out of date.

## Screenshot
![image](https://user-images.githubusercontent.com/46334387/100787430-7ab39f80-33c8-11eb-9992-7aa4d9a67b9e.png)

 * Running PoP OS 20.10

**Comment by ogra1** [comment]
yeah, sorry, i did not have the time to test the (automatically built) version in the edge channel until the weekend, i have released it to stable now ... if it bothers you you can just easily switch to edge the next time this occurs by using:

    sudo snap refresh --edge zoom-client

and switch back to the stable version once the edge one got promoted with:

    sudo snap refresh --stable zoom-client 

thanks a lot for the reminder thought !
