### ISSUE TITLE
ZOOM 5.4.6 is not letting me join meetings

### ISSUE THREAD

**Issue by Bill192** [ogra1/zoom-snap#65]
I recently updated zoom because of problems with it not starting. I have been having trouble when i am joining my class for school that when they admit me in the class it tries to connect but it does not connect. My OS is Ubuntu 20.04.1 LTS 64 bit. The thing i find weird is that i am able to host meetings and every things works normally. I took a look at my fire wall to see if it was getting stuck but nothing. 
Please let me now what may be the issue. 
If you need more info let me know.

**Comment by Fuseteam** [comment]
you updated zoom? are you using the snap version or the deb version? this is the repo for the snap version

**Comment by Bill192** [comment]
the snap

**Comment by Fuseteam** [comment]
snap automatically updates fwiw
i'm assuming its an issue with it being stuck at "loading" for a while? does when you join a meeting? or when you login before joining the meeting?
i noticed a similar issue on the deb version but assumed it was an network issue

**Comment by Bill192** [comment]
I had the same idea but i am not sure because when i am joining someone meeting it spines and the longest  waited for fun was 30 minutes and then gave up. But what i still find weird is when login in or starting my own meeting it takes less the a second to load.

**Comment by Fuseteam** [comment]
yeah its weird

**Comment by Bill192** [comment]
I have forgotten about AppArmor and i did a reboot and tested it and it works I will see tomorrow if its fixed and i will closed the ticket if its all good.

**Comment by Fuseteam** [comment]
apparmor? now that would be an interesting find

**Comment by Bill192** [comment]
`sudo service apparmor reload`

this is what fixed it i am also surprised but i know people had problems with it with other apps.

**Comment by Fuseteam** [comment]
huh interesting fix
