### ISSUE TITLE
Wayland on Gnome NOT supported?

### ISSUE THREAD

**Issue by kalabalik** [ogra1/zoom-snap#67]
Dears,

I am on Ubuntu 20.10 with Wayland and Gnome 3.38.1. Starting today, when I try to share my screen, I get the following message:
`Can not start share, we only support Wayland on GNOME with Ubuntu 17 and above, ... If your OS in not on the list, please use x11 instead`.
Since this should not happen on my machine, I checked the logs which say:
`Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.`

If I do `echo $XDG_SESSION_TYPE` in the terminal, I get "wayland".

Here is the complete log file: [zoom_stdout_stderr.log](https://github.com/ogra1/zoom-snap/files/5791366/zoom_stdout_stderr.log)

What do I do?

**Comment by emon109848** [comment]
Switch to Xorg from Wayland
worked for me

https://www.maketecheasier.com/switch-xorg-wayland-ubuntu1710/

**Comment by Fuseteam** [comment]
perhaps its a simple `export QT_QPA_PLATFORM=wayland`

**Comment by edurojasr** [comment]
Hi

Apparently this problem is more complicated, this issue #22  follow the discussion of the state of Wayland with this snap.

**Comment by ogra1** [comment]
please see my last comment on #22 there is a version that might perhaps fix this issue in the edge channel currently... the other issue has instructions how to switch to it (and back after testing)

**Comment by ogra1** [comment]
The popup message issue is clearly fixed snap revision 146 and above (in the edge channel at the moment) further discussion and testing around this issue should take place in #22 now, i'm closing this one
