### ISSUE TITLE
5.4.9 is released

### ISSUE THREAD

**Issue by validatedev** [ogra1/zoom-snap#68]
![image](https://user-images.githubusercontent.com/29679552/104810505-1462cf00-5806-11eb-95e4-47203b443926.png)

Can you update the snap to the latest? Thanks.

**Comment by Fuseteam** [comment]
what does `snap info zoom-client` say?

**Comment by validatedev** [comment]
```
name:      zoom-client
summary:   ZOOM Cloud Meetings
publisher: Oliver Grawert (ogra)
store-url: https://snapcraft.io/zoom-client
contact:   ogra@ubuntu.com?subject=zoom-client
license:   unset
description: |
  Video conferencing with real-time messaging and content sharing
  
  https://zoom.us provides simplified video conferencing, whiteboard sharing
  and messaging across any device. This is an unofficial re-pack of the
  debian
  package provided by zoom.us
  
  The source code for the snap package can be found at
  https://github.com/ogra1/zoom-snap
  
  Please file issues under https://github.com/ogra1/zoom-snap/issues
commands:
  - zoom-client
snap-id:      76rrD7USwCJrZgepbRk7UdFEWON3tVKX
tracking:     latest/stable
refresh-date: 3 days ago, at 22:21 +03
channels:
  latest/stable:    5.4.57450.1220 2020-12-23 (125) 245MB -
  latest/candidate: 5.4.53350.1027 2020-10-31 (108) 157MB -
  latest/beta:      5.4.53350.1027 2020-10-31 (108) 157MB -
  latest/edge:      5.4.57862.0110 2021-01-16 (128) 245MB -
installed:          5.4.57450.1220            (125) 245MB -
```

**Comment by validatedev** [comment]
`snap refresh` outputs `All snaps up to date.`

**Comment by ogra1** [comment]
if it is important for you to have it installed before it has been tested (or want to help testing) you can always switch to the edge channel with:

    sudo snap refresh --edge zoom-client

likewise you can switch back to the stable channel (once the package has been tested and released to stable) with:

    sudo snap refresh --stable zoom-client

the 5.4.57862.0110 version (revision 125) has now been released to stable

**Comment by Fuseteam** [comment]
@ogra1 I thought it was about 5.4**.9**?
wait now I look at the image again it says 5.4.9 (57862.0110) :thinking:

**Comment by ogra1** [comment]
seems like ... my scripts only check the build ID (the number in brackets) ... if you check the about window in zoom it also says "5.4.9 (57862.0110)" now ... i should probably make the scripts get the actual version number somehow, but zoom only provides the build ID in its version.txt file inside the package:

https://github.com/ogra1/zoom-snap/blob/master/snap/snapcraft.yaml#L122
