### ISSUE TITLE
Unable to switch audio input and output channels

### ISSUE THREAD

**Issue by tkazik** [ogra1/zoom-snap#7]
Hi Oliver

First, thank you for fixing [this](https://github.com/ogra1/zoom-snap/issues/2)!
Unfortunately, there is another thing that is still not working properly:
In settings, I am not able to adjust the input and output channels (the dropdown is inactive). Any pointer?
![screenshot](https://user-images.githubusercontent.com/15689124/79052732-ce565a80-7c38-11ea-93bb-11b049c6e3d2.png)
Some more info: Ubuntu 18.04.4, all permissions granted for zoom, micro and headphone are working (no driver issues).

Thank you!

**Comment by ogra1** [comment]
hmm, zoom just talks to your local pulseaudio server (and this works on my test desktop with 4 different audio devices). do you have any exotic setup (replaced pulse with jackd or running pulse as system soundserver or something similar ?)

**Comment by petevg** [comment]
I'm having what may be a related issue, except that my Zoom client simply freezes when I try to click into the "Audio" tab in settings, or test audio (or join a meeting, for that matter). I'm running the Ubuntu Focal Beta on my system, which is a Thinkpad T480.

I have the following entry in $HOME/snap/zoom-client/current/.zoom/logs/zoom-terminal.log:

`No PulseAudio daemon running, or not running as session daemon.`

I do have a pulseaudio process running, but possibly not as a "session daemon". Here's the relevant entry from `systemctl status`

```
           │ │ │ ├─pulseaudio.service 
           │ │ │ │ └─5184 /usr/bin/pulseaudio --daemonize=no
```
(That's part of a tree running under my userid.)

I don't remember having done anything unusual with pulseaudio, other than editing a config file at one point to switch the left and right channels on my headphones. The system has been through several Ubuntu release upgrades and plenty of tinkering, though, so I may be forgetting having done something.

**Comment by tkazik** [comment]
No fancy setup: Basically 18.04.4 out of the box. Generally the app feels quite unresponsive and slow. But I do not get any errors or warning when launching the app from the console.

**Comment by ogra1** [comment]
can you attach your 
```
~/snap/zoom-client/current/.zoom/logs/zoom-terminal.log
```
lets see if there are any errors 

(ignore the "No PulseAudio daemon running, or not running as session daemon." (zoom runs qtdiag before starting which tries a check for the existence of a pid file before connecting to the pulse socket but connects anyway...))

**Comment by tkazik** [comment]
Sure, here it is (I just renamed the username and MacAddr :)):

[zoom-terminal.log](https://github.com/ogra1/zoom-snap/files/4499107/zoom-terminal.log)

Thank you for your investigations!

**Comment by tkazik** [comment]
Working now...
The easiest setup for me:

- Leave the settings in zoom as `same as system` (for both speaker & microphone)
- Use this [extension](https://extensions.gnome.org/extension/906/sound-output-device-chooser/) to change input/output quickly

Thx for your support!
