### ISSUE TITLE
Push to talk

### ISSUE THREAD

**Issue by misokt** [ogra1/zoom-snap#70]
Is this feature unavailable in this snap package? If so, do we expect to get this feature in the future?
If it is available please redirect me to where I should be looking to enable it, thank you.

Info:
Pop 20.04
Linux 5.8.0-7630-generic

**Comment by Fuseteam** [comment]
@opp if it is available in the deb variant it is available in the snap variant. i don't recall this feature being in available in the desktop version of zoom, but I may be mistaken
