### ISSUE TITLE
Use Github action to publish snap security updates quicker

### ISSUE THREAD

**Issue by calderonth** [ogra1/zoom-snap#76]
Hello,

I'm not sure what's the process to publish updates to the snap package but I can see you're not using Github actions to do that.
Is there a reason why you wouldn't leverage this to accelerate updates to be rolled out for users of zoom-client on snap?
Is this a manual process?

For instance `5.6.3` is available for Linux fixing security bugs:
```
curl -I https://zoom.us/client/latest/zoom_amd64.deb             
HTTP/2 302 
date: Tue, 20 Apr 2021 16:32:37 GMT
location: https://cdn.zoom.us/prod/5.6.16775.0418/zoom_amd64.deb
```

Cheers,

Thomas

**Comment by ogra1** [comment]
The snap builds are automatically done on https://build-snapcraft.io (like all/most other snaps) within 24h (at most) after a new zoom release came out and are released to the edge channel... then an automated test is triggered, after which i do manual regression testing and then release it to the stable channel ... if you are concerned that the manual testing before a stable release takes too long for you, you can switch your snap to the edge channel (indeed involving the risk that you hit regressions that are only catched before the stable release is done).

i don not see a reason to switch to a non-standard CI infrastructure (for snaps that is) for no extra benefit here ... (it wont speed up the testing after all and the edge builds should happen at the same time with either build infra)

if you want to watch the builds directly, the snap build can be seen at:

https://launchpad.net/~build.snapcraft.io/+snap/8945c491a02ce87321c5fed28c171d3b
