### ISSUE TITLE
Custom virtual backgrounds get lost on upgrade

### ISSUE THREAD

**Issue by castrojo** [ogra1/zoom-snap#8]
Zoom has a feature to let you use a virtual background, you can do this by clicking "+ Add image" in the Virtual Background setting and then adding some custom backgrounds. (They're like wallpapers).

When Zoom gets upgraded however, all of the added images disappear, as if the app has reset. I add my wallpapers from `~/Pictures`. I'm not sure if this intentional or not or just a side effect from the sandboxing. Not sure if I should be putting the backgrounds in a specific place, I'm also not sure if Zoom references the background via or makes a copy for itself.

**Comment by ogra1** [comment]
do any other settings disappear or is it only the pictures ? 

zoom seems to store a copy as TIFF in ```~/snap/zoom-client/current/.zoom/data/VirtualBkgnd_Custom``` when you add a new background.
i wonder if there is some snapd bug with copying forward hidden directories (that would mean it affects more settings) or if it has something to do with the curly brackets in the filenames of these files.

**Comment by castrojo** [comment]
Other settings are unaffected. Also interesting, when I looked in `~/snap/zoom-client/current/.zoom/data/VirtualBkgnd_Custom` all the old images are there (with their timestamps preserved when I added them), so they're on the disk, just seems like Zoom forgot about them?

**Comment by l30n4rd007** [comment]
yes, reactions is not available to, i have version 5.0.399860.0429, my son will  very happy with the fix it
thanks you for your help 




> do any other settings disappear or is it only the pictures ?
> 
> zoom seems to store a copy as TIFF in `~/snap/zoom-client/current/.zoom/data/VirtualBkgnd_Custom` when you add a new background.
> i wonder if there is some snapd bug with copying forward hidden directories (that would mean it affects more settings) or if it has something to do with the curly brackets in the filenames of these files.

**Comment by castrojo** [comment]
I think this is app specific and not packaging specific, I've had upgrades on Zoom in Windows exhibit the behavior, you can probably close this.

**Comment by ogra1** [comment]
thanks for the feedback ... doing so ...

**Comment by Moilleadoir** [comment]
It’s a pity Zoom has no open bug tracking, but I’ve reported this. I don’t expect it to get fixed though.
