### ISSUE TITLE
SSO for zoomgov not working

### ISSUE THREAD

**Issue by Septem151** [ogra1/zoom-snap#90]
## Operating System
Ubuntu 20.04 LTS

## Zoom Version
5.7.4-28991.0726

## Issue
I'm unable to login via SSO. There's no option to select ".zoomgov.com" as the SSO domain, and manually entering my email states there's no such domain because it's looking for COMPANY.zoom.us instead of COMPANY.zoomgov.com

Manually replacing the correct domain in the SSO URL lets me get to the SSO's login page, which opens zoom via xdg-open, but Zoom spins forever then says "Timeout" since it's internally still trying to use COMPANY.zoom.us as the domain.

This was not an issue on Zoom version 5.1.4. I've tried manually editing the zoomus.conf file as well as trying the non-snap version.

**Comment by Fuseteam** [comment]
wait is it also failing on the non-snap version?

**Comment by Septem151** [comment]
> wait is it also failing on the non-snap version?

Yes. I've tried both snap and non-snap version, both Version 5.4.2 (53391.1108) and Version 5.7.4 (28991.0726). On another computer, I have an older version installed, Version 5.1.4 (18436.0628) which does not have this issue.

**Comment by Septem151** [comment]
Manually setting `conf.webserver=https://www.zoomgov.com` and `conf.webserver.vendor.default=https://COMPANY.zoomgov.com` seems to work around this, but I have to do this *every time I login/open Zoom*

**Comment by Fuseteam** [comment]
if its also broken in the none snap version, there's actually nothing the maintainer this repository can actually do about it. this repository handles just the packaging.

in other words, this is an bug of the zoom client itself and should be reported to the zoom devs. the zoom devs don't pay attention to this issue tracker

**Comment by Septem151** [comment]
Figured it out with the help of zoom support. For those that run across this issue in the future, the solution is to add the following line to your `zoomus.conf` file:
```
enableCloudSwitch=true
```
