### ISSUE TITLE
Chat not functioning since 5.8.0.16 update

### ISSUE THREAD

**Issue by robertross-net** [ogra1/zoom-snap#91]
Neither I (Ubuntu 21.04) nor two parties for whom I'd installed zoom-client (Ubuntu 20.04) are able to use the Chat function since an update to 5.8.0.16 came along on 23 Sept. The Chat window is present but appears different from normal: Instead of a left sidebar with chats on the right, there is only a list of recent chats. There are options to "Meet with video" and "Meet without video" as well as a small handful of other options in a drop-down menu; but no way to initiate a chat nor access past chats.

I have installed 5.8.0.16 directly from ZOOM via a provided .deb package and everything works fine.

**Comment by j0xaf** [comment]
@robertross-net is the snap working for you now? If yes, could you share your solution? Thx!

**Comment by robertross-net** [comment]
@j0xaf After removing the Snap and (re-?)installing 5.6.1.16 using apt (which worked fine) I tried the Snap once again last evening and found the Snap to be 5.6.1 with a working chat.
